version: '3.8'

services:
  solana-trading:
    build: .
    container_name: solana-trading-server
    restart: always
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
